using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Windows.Forms;

namespace Group_Project.PublicViewUserControls
{
    /// <summary>
    /// a usercontrol that allows users to view a team's position in a league.
    /// </summary>
    public partial class LeagueView : UserControl
    {
        /// <summary>
        /// Autogenerated code.
        /// </summary>
        public LeagueView()
        {
            InitializeComponent();
        }
        /// <summary>
        /// code to update the usercontrol
        /// </summary>
        /// <param name="Teams">A Class Containing all of the league position details</param>
        public void update(List<Classes.Team> Teams)
        {
            dgvLeaguePositions.DataSource = Teams.Select(o => new Classes.LeagueTableDisplay() { Name = o.TeamName, GP = o.Matches, W = o.GamesWon, D = o.GamesDrawn, L = o.GamesLost, GF = o.GoalsFor, GA = o.GoalsAgainst, Pts = o.Points }).ToList();
        }
        /// <summary>
        /// Code to change the colour of all the controls on the usercontrol
        /// </summary>
        public void ChangeColour()
        {
            ColourChange.ColourPanel(pnlMain);
            ColourChange.ColourPanel(pnlTitle);
            ColourChange.ColourLabel(lblTitle);
            ColourChange.ColourDGV(dgvLeaguePositions);
        }
    }

    //TD: Sort by points
}
