using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Windows.Forms;

namespace Group_Project.UserControls
{
    public partial class PasswordControlView : UserControl
    {
        /// <summary>
        /// autogenerated code
        /// </summary>
        public PasswordControlView()
        {
            InitializeComponent();
        }
        /// <summary>
        /// A list of classes containing the entire password table, bar the passwords, to aviod them being discovered
        /// </summary>
        List<Classes.Password> Passwords;
        /// <summary>
        /// A list of classes containing all of the teams
        /// </summary>
        List<Classes.TeamDetails> TeamList;
        /// <summary>
        /// integer to store whether the user is adding or editing a record (1 for adding, 2 for editing)
        /// </summary>
        public int EditMode;
        /// <summary>
        /// String to hold the username of the user being edited
        /// </summary>
        public string Edituser;

        #region Update Handling
        /// <summary>
        /// Fill the lists and update the usercontrol
        /// </summary>
        public void update()
        {
            Database.DatabaseConnection.dbConnect();
            TeamList = Database.TeamList.AllTeams();
            Passwords = Database.PasswordList.Fill();
            Database.DatabaseConnection.dbDisconnect();
            dgvPasswords.DataSource = Passwords.Select(o => new Classes.PasswordTableDisplay() { Name = o.Username, Access_Level = o.AccessRights }).ToList();
        }
        /// <summary>
        /// An event to handle passing the update command to the parent form
        /// </summary>
        public event EventHandler UpdateView;
        /// <summary>
        /// A method to handle passing the update command to the parent form without incurring exceptions
        /// </summary>
        /// <param name="sender">Sending Object</param>
        /// <param name="e">Event Argument</param>
        protected void UpdateParent(object sender, EventArgs e)
        {
            if (this.UpdateView != null)
                this.UpdateView(this, e);
        }
        #endregion

        #region Utility Functions
        /// <summary>
        /// a utility function to switch between editing/adding mode or not
        /// </summary>
        /// <param name="access">false for editing, true to return to normal</param>
        private void DetailsAccess(bool access)
        {
            dgvPasswords.Enabled = access;
            txtUsername.ReadOnly = access;
            txtPassword.ReadOnly = access;
            txtPasswordVerfic.ReadOnly = access;
            cboAccess.Items.Clear();
            if (!access)
            {
                cboAccess.SelectedText = "";
                cboAccess.Items.Add("ADMINISTRATOR");
                foreach (Classes.TeamDetails Team in TeamList)
                {
                    cboAccess.Items.Add(Team.TeamID);
                }
            }
            pnlEdit.Visible = !access;
            pnlStandard.Visible = access;
        }
        /// <summary>
        /// code that changes the colour of the controls
        /// </summary>
        public void colourChange()
        {
            ColourChange.ColourSplitPanel(splitContainer1);
            ColourChange.ColourPanel(pnlAdmin);
            ColourChange.ColourPanel(pnlEdit);
            ColourChange.ColourPanel(pnlStandard);
            ColourChange.ColourTextbox(txtUsername);
            ColourChange.ColourTextbox(txtPassword);
            ColourChange.ColourTextbox(txtPasswordVerfic);
            ColourChange.ColourCombobox(cboAccess);
            ColourChange.ColourLabel(lblAccess);
            ColourChange.ColourLabel(lblCurrentLogins);
            ColourChange.ColourLabel(lblPassword);
            ColourChange.ColourLabel(lblPasswordVerific);
            ColourChange.ColourLabel(lblUsername);
            ColourChange.ColourDGV(dgvPasswords);
            ColourChange.ColourButton(cmdAdd);
            ColourChange.ColourButton(cmdCancel);
            ColourChange.ColourButton(cmdConfirm);
            ColourChange.ColourButton(cmdDelete);
            ColourChange.ColourButton(cmdDelete);
            ColourChange.ColourButton(cmdUpdate);
        }
        #endregion

        #region Object Code
        /// <summary>
        /// when a different Username is selected, change the textboxes to display the new record. 
        /// </summary>
        /// <param name="sender">Sending Object</param>
        /// <param name="e">Event Arguement</param>
        private void dgvPasswords_SelectionChanged(object sender, EventArgs e)
        {
            cboAccess.Items.Clear();
            if (dgvPasswords.SelectedRows.Count > 0)
            {
                txtUsername.Text = dgvPasswords.SelectedRows[0].Cells[0].Value.ToString();
                cboAccess.Items.Add(dgvPasswords.SelectedRows[0].Cells[1].Value.ToString());
                cboAccess.SelectedIndex = 0;
            }
            else
            {
                txtUsername.Text = txtPassword.Text = txtPasswordVerfic.Text = "";
            }
        }
        /// <summary>
        /// When the add button is clicked, change to editing mode and remember that a record is to be added
        /// </summary>
        /// <param name="sender">Sending Object</param>
        /// <param name="e">Event Arguements</param>
        private void cmdAdd_Click(object sender, EventArgs e)
        {
            DetailsAccess(false);
            EditMode = 1;
        }
        /// <summary>
        /// When the update button is clicked, change to editing mode and remember that a record is to be edited, and which record is being changed
        /// </summary>
        /// <param name="sender">Sending Object</param>
        /// <param name="e">Event Arguements</param>
        private void cmdUpdate_Click(object sender, EventArgs e)
        {
            DetailsAccess(false);
            EditMode = 2;
            Edituser = txtUsername.Text;
        }
        /// <summary>
        /// When the Delete button is clicked, Connect to the database and delete the record then tell the parent form to update.
        /// </summary>
        /// <param name="sender">Sending Object</param>
        /// <param name="e">Event Arguements</param>
        private void cmdDelete_Click(object sender, EventArgs e)
        {
            Database.DatabaseConnection.dbConnect();
            Database.PasswordList.Delete(txtUsername.Text);
            Database.DatabaseConnection.dbDisconnect();
            UpdateParent(this, e);
        }
        /// <summary>
        /// On clicking the accept button, check whether the user was editing or adding a record, then connect to the database and use the changes.
        /// </summary>
        /// <param name="sender">Sending Object</param>
        /// <param name="e">Event Argument</param>
        private void cmdConfirm_Click(object sender, EventArgs e)
        {
            if (txtPassword.Text == txtPasswordVerfic.Text)
            {
                DetailsAccess(true);
                Database.DatabaseConnection.dbConnect();
                switch (EditMode)
                {
                    case 0:
                        MessageBox.Show("Error: Attempted Invalid Command", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        break;
                    case 1:
                        Database.PasswordList.Add(txtUsername.Text, txtPassword.Text, cboAccess.Text);
                        break;
                    case 2:
                        Database.PasswordList.Update(txtUsername.Text, txtPassword.Text, cboAccess.Text);
                        break;
                    default:
                        MessageBox.Show("Error: Attempted Invalid Command", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        break;
                }
                Database.DatabaseConnection.dbDisconnect();
                EditMode = 0;
                UpdateParent(this, e);
            }
            else MessageBox.Show("Error: Password and Password Verification do not contain the same text.", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
        /// <summary>
        /// On clicking the cancel button, return the form to normal
        /// </summary>
        /// <param name="sender">Sending Object</param>
        /// <param name="e">Event Argument</param>
        private void cmdCancel_Click(object sender, EventArgs e)
        {
            DetailsAccess(true);
            EditMode = 0;
            UpdateParent(this, e);
        }
        #endregion

        //TD: handle two identical usernames
    }
}
